// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/library.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ExportProgress> dco_decode_StreamSink_export_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<IndexProgress> dco_decode_StreamSink_index_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PreprocessProgress>
  dco_decode_StreamSink_preprocess_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  BurstSummary dco_decode_burst_summary(dynamic raw);

  @protected
  CacheStatus dco_decode_cache_status(dynamic raw);

  @protected
  ExportPlan dco_decode_export_plan(dynamic raw);

  @protected
  ExportProgress dco_decode_export_progress(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IndexProgress dco_decode_index_progress(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BurstSummary> dco_decode_list_burst_summary(dynamic raw);

  @protected
  List<PhotoSummary> dco_decode_list_photo_summary(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SourceInfo> dco_decode_list_source_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PhotoSummary dco_decode_photo_summary(dynamic raw);

  @protected
  PreprocessProgress dco_decode_preprocess_progress(dynamic raw);

  @protected
  ProgressStats dco_decode_progress_stats(dynamic raw);

  @protected
  SourceInfo dco_decode_source_info(dynamic raw);

  @protected
  SplitResult dco_decode_split_result(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ExportProgress> sse_decode_StreamSink_export_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<IndexProgress> sse_decode_StreamSink_index_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PreprocessProgress>
  sse_decode_StreamSink_preprocess_progress_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  BurstSummary sse_decode_burst_summary(SseDeserializer deserializer);

  @protected
  CacheStatus sse_decode_cache_status(SseDeserializer deserializer);

  @protected
  ExportPlan sse_decode_export_plan(SseDeserializer deserializer);

  @protected
  ExportProgress sse_decode_export_progress(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IndexProgress sse_decode_index_progress(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BurstSummary> sse_decode_list_burst_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<PhotoSummary> sse_decode_list_photo_summary(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SourceInfo> sse_decode_list_source_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PhotoSummary sse_decode_photo_summary(SseDeserializer deserializer);

  @protected
  PreprocessProgress sse_decode_preprocess_progress(
    SseDeserializer deserializer,
  );

  @protected
  ProgressStats sse_decode_progress_stats(SseDeserializer deserializer);

  @protected
  SourceInfo sse_decode_source_info(SseDeserializer deserializer);

  @protected
  SplitResult sse_decode_split_result(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_export_progress_Sse(
    RustStreamSink<ExportProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_index_progress_Sse(
    RustStreamSink<IndexProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_preprocess_progress_Sse(
    RustStreamSink<PreprocessProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_burst_summary(BurstSummary self, SseSerializer serializer);

  @protected
  void sse_encode_cache_status(CacheStatus self, SseSerializer serializer);

  @protected
  void sse_encode_export_plan(ExportPlan self, SseSerializer serializer);

  @protected
  void sse_encode_export_progress(
    ExportProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_index_progress(IndexProgress self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_burst_summary(
    List<BurstSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_photo_summary(
    List<PhotoSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_info(
    List<SourceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_photo_summary(PhotoSummary self, SseSerializer serializer);

  @protected
  void sse_encode_preprocess_progress(
    PreprocessProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_progress_stats(ProgressStats self, SseSerializer serializer);

  @protected
  void sse_encode_source_info(SourceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_split_result(SplitResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
