// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/library.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiLibraryInitLibrary();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 791109207;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_photo_review_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiLibraryCancelExport();

  Future<void> crateApiLibraryCancelPreprocess();

  Future<String?> crateApiLibraryGetAppSetting({required String key});

  Future<List<PhotoSummary>> crateApiLibraryGetBurstFrames({
    required PlatformInt64 sourceId,
    required PlatformInt64 burstId,
  });

  Future<CacheStatus> crateApiLibraryGetCacheStatus({
    required PlatformInt64 sourceId,
  });

  Future<String?> crateApiLibraryGetCachedStill({
    required PlatformInt64 sourceId,
    required PlatformInt64 photoId,
  });

  Future<ProgressStats> crateApiLibraryGetProgressStats({
    required PlatformInt64 sourceId,
  });

  Future<void> crateApiLibraryInitDb({required String dbPath});

  Future<void> crateApiLibraryInitLibrary();

  Future<List<BurstSummary>> crateApiLibraryListBursts({
    required PlatformInt64 sourceId,
    String? statusFilter,
    required PlatformInt64 offset,
    required PlatformInt64 limit,
  });

  Future<List<PhotoSummary>> crateApiLibraryListSingles({
    required PlatformInt64 sourceId,
    required PlatformInt64 offset,
    required PlatformInt64 limit,
  });

  Future<List<SourceInfo>> crateApiLibraryListSources();

  Future<PlatformInt64> crateApiLibraryMergeBursts({
    required Int64List burstIds,
  });

  Future<ExportPlan> crateApiLibraryPlanExport({
    required PlatformInt64 sourceId,
  });

  Future<BigInt> crateApiLibraryRegroup({
    required PlatformInt64 sourceId,
    required PlatformInt64 gapMs,
    required PlatformInt64 minBurstLen,
  });

  Future<SourceInfo> crateApiLibrarySelectSource({required String rootPath});

  Future<void> crateApiLibrarySetAppSetting({
    required String key,
    required String value,
  });

  Future<void> crateApiLibrarySetBurstStatus({
    required PlatformInt64 burstId,
    required String status,
  });

  Future<void> crateApiLibrarySetCacheFolder({
    required PlatformInt64 sourceId,
    required String path,
  });

  Future<void> crateApiLibrarySetExportRate({
    required PlatformInt64 burstId,
    required double rate,
  });

  Future<void> crateApiLibrarySetFrameKeep({
    required Int64List photoIds,
    required bool keep,
  });

  Future<void> crateApiLibrarySetKeepVideo({
    required PlatformInt64 burstId,
    required bool keep,
  });

  Future<void> crateApiLibrarySetOutputFolder({
    required PlatformInt64 sourceId,
    required String path,
  });

  Future<SplitResult> crateApiLibrarySplitBurst({
    required PlatformInt64 burstId,
    required PlatformInt64 atFrameIndex,
  });

  Stream<ExportProgress> crateApiLibraryStartExport({
    required PlatformInt64 sourceId,
  });

  Stream<IndexProgress> crateApiLibraryStartIndex({
    required PlatformInt64 sourceId,
  });

  Stream<PreprocessProgress> crateApiLibraryStartPreprocess({
    required PlatformInt64 sourceId,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiLibraryCancelExport() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryCancelExportConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryCancelExportConstMeta =>
      const TaskConstMeta(debugName: "cancel_export", argNames: []);

  @override
  Future<void> crateApiLibraryCancelPreprocess() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryCancelPreprocessConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryCancelPreprocessConstMeta =>
      const TaskConstMeta(debugName: "cancel_preprocess", argNames: []);

  @override
  Future<String?> crateApiLibraryGetAppSetting({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryGetAppSettingConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetAppSettingConstMeta =>
      const TaskConstMeta(debugName: "get_app_setting", argNames: ["key"]);

  @override
  Future<List<PhotoSummary>> crateApiLibraryGetBurstFrames({
    required PlatformInt64 sourceId,
    required PlatformInt64 burstId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_i_64(burstId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_photo_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryGetBurstFramesConstMeta,
        argValues: [sourceId, burstId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetBurstFramesConstMeta =>
      const TaskConstMeta(
        debugName: "get_burst_frames",
        argNames: ["sourceId", "burstId"],
      );

  @override
  Future<CacheStatus> crateApiLibraryGetCacheStatus({
    required PlatformInt64 sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cache_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryGetCacheStatusConstMeta,
        argValues: [sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetCacheStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_cache_status",
        argNames: ["sourceId"],
      );

  @override
  Future<String?> crateApiLibraryGetCachedStill({
    required PlatformInt64 sourceId,
    required PlatformInt64 photoId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_i_64(photoId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryGetCachedStillConstMeta,
        argValues: [sourceId, photoId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetCachedStillConstMeta =>
      const TaskConstMeta(
        debugName: "get_cached_still",
        argNames: ["sourceId", "photoId"],
      );

  @override
  Future<ProgressStats> crateApiLibraryGetProgressStats({
    required PlatformInt64 sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_stats,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryGetProgressStatsConstMeta,
        argValues: [sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetProgressStatsConstMeta =>
      const TaskConstMeta(
        debugName: "get_progress_stats",
        argNames: ["sourceId"],
      );

  @override
  Future<void> crateApiLibraryInitDb({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryInitDbConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryInitDbConstMeta =>
      const TaskConstMeta(debugName: "init_db", argNames: ["dbPath"]);

  @override
  Future<void> crateApiLibraryInitLibrary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryInitLibraryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryInitLibraryConstMeta =>
      const TaskConstMeta(debugName: "init_library", argNames: []);

  @override
  Future<List<BurstSummary>> crateApiLibraryListBursts({
    required PlatformInt64 sourceId,
    String? statusFilter,
    required PlatformInt64 offset,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_opt_String(statusFilter, serializer);
          sse_encode_i_64(offset, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_burst_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryListBurstsConstMeta,
        argValues: [sourceId, statusFilter, offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListBurstsConstMeta => const TaskConstMeta(
    debugName: "list_bursts",
    argNames: ["sourceId", "statusFilter", "offset", "limit"],
  );

  @override
  Future<List<PhotoSummary>> crateApiLibraryListSingles({
    required PlatformInt64 sourceId,
    required PlatformInt64 offset,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_i_64(offset, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_photo_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryListSinglesConstMeta,
        argValues: [sourceId, offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListSinglesConstMeta => const TaskConstMeta(
    debugName: "list_singles",
    argNames: ["sourceId", "offset", "limit"],
  );

  @override
  Future<List<SourceInfo>> crateApiLibraryListSources() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_source_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryListSourcesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListSourcesConstMeta =>
      const TaskConstMeta(debugName: "list_sources", argNames: []);

  @override
  Future<PlatformInt64> crateApiLibraryMergeBursts({
    required Int64List burstIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_64_strict(burstIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryMergeBurstsConstMeta,
        argValues: [burstIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryMergeBurstsConstMeta =>
      const TaskConstMeta(debugName: "merge_bursts", argNames: ["burstIds"]);

  @override
  Future<ExportPlan> crateApiLibraryPlanExport({
    required PlatformInt64 sourceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_plan,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryPlanExportConstMeta,
        argValues: [sourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryPlanExportConstMeta =>
      const TaskConstMeta(debugName: "plan_export", argNames: ["sourceId"]);

  @override
  Future<BigInt> crateApiLibraryRegroup({
    required PlatformInt64 sourceId,
    required PlatformInt64 gapMs,
    required PlatformInt64 minBurstLen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_i_64(gapMs, serializer);
          sse_encode_i_64(minBurstLen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryRegroupConstMeta,
        argValues: [sourceId, gapMs, minBurstLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryRegroupConstMeta => const TaskConstMeta(
    debugName: "regroup",
    argNames: ["sourceId", "gapMs", "minBurstLen"],
  );

  @override
  Future<SourceInfo> crateApiLibrarySelectSource({required String rootPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_source_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySelectSourceConstMeta,
        argValues: [rootPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySelectSourceConstMeta =>
      const TaskConstMeta(debugName: "select_source", argNames: ["rootPath"]);

  @override
  Future<void> crateApiLibrarySetAppSetting({
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetAppSettingConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetAppSettingConstMeta =>
      const TaskConstMeta(
        debugName: "set_app_setting",
        argNames: ["key", "value"],
      );

  @override
  Future<void> crateApiLibrarySetBurstStatus({
    required PlatformInt64 burstId,
    required String status,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(burstId, serializer);
          sse_encode_String(status, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetBurstStatusConstMeta,
        argValues: [burstId, status],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetBurstStatusConstMeta =>
      const TaskConstMeta(
        debugName: "set_burst_status",
        argNames: ["burstId", "status"],
      );

  @override
  Future<void> crateApiLibrarySetCacheFolder({
    required PlatformInt64 sourceId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetCacheFolderConstMeta,
        argValues: [sourceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetCacheFolderConstMeta =>
      const TaskConstMeta(
        debugName: "set_cache_folder",
        argNames: ["sourceId", "path"],
      );

  @override
  Future<void> crateApiLibrarySetExportRate({
    required PlatformInt64 burstId,
    required double rate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(burstId, serializer);
          sse_encode_f_64(rate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetExportRateConstMeta,
        argValues: [burstId, rate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetExportRateConstMeta =>
      const TaskConstMeta(
        debugName: "set_export_rate",
        argNames: ["burstId", "rate"],
      );

  @override
  Future<void> crateApiLibrarySetFrameKeep({
    required Int64List photoIds,
    required bool keep,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_64_strict(photoIds, serializer);
          sse_encode_bool(keep, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetFrameKeepConstMeta,
        argValues: [photoIds, keep],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetFrameKeepConstMeta =>
      const TaskConstMeta(
        debugName: "set_frame_keep",
        argNames: ["photoIds", "keep"],
      );

  @override
  Future<void> crateApiLibrarySetKeepVideo({
    required PlatformInt64 burstId,
    required bool keep,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(burstId, serializer);
          sse_encode_bool(keep, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetKeepVideoConstMeta,
        argValues: [burstId, keep],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetKeepVideoConstMeta =>
      const TaskConstMeta(
        debugName: "set_keep_video",
        argNames: ["burstId", "keep"],
      );

  @override
  Future<void> crateApiLibrarySetOutputFolder({
    required PlatformInt64 sourceId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sourceId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySetOutputFolderConstMeta,
        argValues: [sourceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySetOutputFolderConstMeta =>
      const TaskConstMeta(
        debugName: "set_output_folder",
        argNames: ["sourceId", "path"],
      );

  @override
  Future<SplitResult> crateApiLibrarySplitBurst({
    required PlatformInt64 burstId,
    required PlatformInt64 atFrameIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(burstId, serializer);
          sse_encode_i_64(atFrameIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_split_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibrarySplitBurstConstMeta,
        argValues: [burstId, atFrameIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySplitBurstConstMeta => const TaskConstMeta(
    debugName: "split_burst",
    argNames: ["burstId", "atFrameIndex"],
  );

  @override
  Stream<ExportProgress> crateApiLibraryStartExport({
    required PlatformInt64 sourceId,
  }) {
    final sink = RustStreamSink<ExportProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_64(sourceId, serializer);
            sse_encode_StreamSink_export_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 25,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiLibraryStartExportConstMeta,
          argValues: [sourceId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLibraryStartExportConstMeta => const TaskConstMeta(
    debugName: "start_export",
    argNames: ["sourceId", "sink"],
  );

  @override
  Stream<IndexProgress> crateApiLibraryStartIndex({
    required PlatformInt64 sourceId,
  }) {
    final sink = RustStreamSink<IndexProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_64(sourceId, serializer);
            sse_encode_StreamSink_index_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 26,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiLibraryStartIndexConstMeta,
          argValues: [sourceId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLibraryStartIndexConstMeta => const TaskConstMeta(
    debugName: "start_index",
    argNames: ["sourceId", "sink"],
  );

  @override
  Stream<PreprocessProgress> crateApiLibraryStartPreprocess({
    required PlatformInt64 sourceId,
  }) {
    final sink = RustStreamSink<PreprocessProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_64(sourceId, serializer);
            sse_encode_StreamSink_preprocess_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 27,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiLibraryStartPreprocessConstMeta,
          argValues: [sourceId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLibraryStartPreprocessConstMeta =>
      const TaskConstMeta(
        debugName: "start_preprocess",
        argNames: ["sourceId", "sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ExportProgress> dco_decode_StreamSink_export_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<IndexProgress> dco_decode_StreamSink_index_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PreprocessProgress>
  dco_decode_StreamSink_preprocess_progress_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  BurstSummary dco_decode_burst_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return BurstSummary(
      id: dco_decode_i_64(arr[0]),
      startMs: dco_decode_i_64(arr[1]),
      endMs: dco_decode_i_64(arr[2]),
      frameCount: dco_decode_i_64(arr[3]),
      fpsEstimate: dco_decode_opt_box_autoadd_f_64(arr[4]),
      status: dco_decode_String(arr[5]),
      keepVideo: dco_decode_bool(arr[6]),
      exportRate: dco_decode_f_64(arr[7]),
      keptCount: dco_decode_i_64(arr[8]),
      heroPhotoId: dco_decode_i_64(arr[9]),
      heroDisplayPath: dco_decode_opt_String(arr[10]),
      heroDisplayKind: dco_decode_opt_String(arr[11]),
      heroThumbPath: dco_decode_opt_String(arr[12]),
      videoCachePath: dco_decode_opt_String(arr[13]),
    );
  }

  @protected
  CacheStatus dco_decode_cache_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CacheStatus(
      stillsTotal: dco_decode_u_64(arr[0]),
      stillsCached: dco_decode_u_64(arr[1]),
      videosTotal: dco_decode_u_64(arr[2]),
      videosCached: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  ExportPlan dco_decode_export_plan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ExportPlan(
      keeperPhotos: dco_decode_u_64(arr[0]),
      keeperFiles: dco_decode_u_64(arr[1]),
      keeperBytes: dco_decode_u_64(arr[2]),
      videos: dco_decode_u_64(arr[3]),
      videoBytes: dco_decode_u_64(arr[4]),
      outputPath: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  ExportProgress dco_decode_export_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ExportProgress(
      phase: dco_decode_String(arr[0]),
      done: dco_decode_u_64(arr[1]),
      total: dco_decode_u_64(arr[2]),
      current: dco_decode_String(arr[3]),
      finished: dco_decode_bool(arr[4]),
      filesCopied: dco_decode_u_64(arr[5]),
      filesSkipped: dco_decode_u_64(arr[6]),
      filesRenamed: dco_decode_u_64(arr[7]),
      videosCopied: dco_decode_u_64(arr[8]),
      videosSkipped: dco_decode_u_64(arr[9]),
      failures: dco_decode_list_String(arr[10]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IndexProgress dco_decode_index_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return IndexProgress(
      phase: dco_decode_String(arr[0]),
      done: dco_decode_u_64(arr[1]),
      total: dco_decode_u_64(arr[2]),
      finished: dco_decode_bool(arr[3]),
      photos: dco_decode_u_64(arr[4]),
      bursts: dco_decode_u_64(arr[5]),
      singles: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BurstSummary> dco_decode_list_burst_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_burst_summary).toList();
  }

  @protected
  List<PhotoSummary> dco_decode_list_photo_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_photo_summary).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SourceInfo> dco_decode_list_source_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_source_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PhotoSummary dco_decode_photo_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PhotoSummary(
      id: dco_decode_i_64(arr[0]),
      captureTimeMs: dco_decode_i_64(arr[1]),
      frameIndex: dco_decode_opt_box_autoadd_i_64(arr[2]),
      keep: dco_decode_bool(arr[3]),
      sharpness: dco_decode_opt_box_autoadd_f_64(arr[4]),
      displayPath: dco_decode_String(arr[5]),
      displayKind: dco_decode_String(arr[6]),
      thumbPath: dco_decode_opt_String(arr[7]),
      previewPath: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  PreprocessProgress dco_decode_preprocess_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return PreprocessProgress(
      phase: dco_decode_String(arr[0]),
      done: dco_decode_u_64(arr[1]),
      total: dco_decode_u_64(arr[2]),
      failed: dco_decode_u_64(arr[3]),
      finished: dco_decode_bool(arr[4]),
      stillsProcessed: dco_decode_u_64(arr[5]),
      stillsSkipped: dco_decode_u_64(arr[6]),
      videosRendered: dco_decode_u_64(arr[7]),
      videosSkipped: dco_decode_u_64(arr[8]),
      failures: dco_decode_list_String(arr[9]),
    );
  }

  @protected
  ProgressStats dco_decode_progress_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProgressStats(
      totalBursts: dco_decode_i_64(arr[0]),
      decidedBursts: dco_decode_i_64(arr[1]),
      totalSingles: dco_decode_i_64(arr[2]),
      keptPhotos: dco_decode_i_64(arr[3]),
      keptVideos: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  SourceInfo dco_decode_source_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SourceInfo(
      id: dco_decode_i_64(arr[0]),
      rootPath: dco_decode_String(arr[1]),
      outputPath: dco_decode_opt_String(arr[2]),
      cachePath: dco_decode_opt_String(arr[3]),
      lastIndexedAt: dco_decode_opt_box_autoadd_i_64(arr[4]),
    );
  }

  @protected
  SplitResult dco_decode_split_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SplitResult(
      firstBurstId: dco_decode_i_64(arr[0]),
      secondBurstId: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ExportProgress> sse_decode_StreamSink_export_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<IndexProgress> sse_decode_StreamSink_index_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PreprocessProgress>
  sse_decode_StreamSink_preprocess_progress_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  BurstSummary sse_decode_burst_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_startMs = sse_decode_i_64(deserializer);
    var var_endMs = sse_decode_i_64(deserializer);
    var var_frameCount = sse_decode_i_64(deserializer);
    var var_fpsEstimate = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_keepVideo = sse_decode_bool(deserializer);
    var var_exportRate = sse_decode_f_64(deserializer);
    var var_keptCount = sse_decode_i_64(deserializer);
    var var_heroPhotoId = sse_decode_i_64(deserializer);
    var var_heroDisplayPath = sse_decode_opt_String(deserializer);
    var var_heroDisplayKind = sse_decode_opt_String(deserializer);
    var var_heroThumbPath = sse_decode_opt_String(deserializer);
    var var_videoCachePath = sse_decode_opt_String(deserializer);
    return BurstSummary(
      id: var_id,
      startMs: var_startMs,
      endMs: var_endMs,
      frameCount: var_frameCount,
      fpsEstimate: var_fpsEstimate,
      status: var_status,
      keepVideo: var_keepVideo,
      exportRate: var_exportRate,
      keptCount: var_keptCount,
      heroPhotoId: var_heroPhotoId,
      heroDisplayPath: var_heroDisplayPath,
      heroDisplayKind: var_heroDisplayKind,
      heroThumbPath: var_heroThumbPath,
      videoCachePath: var_videoCachePath,
    );
  }

  @protected
  CacheStatus sse_decode_cache_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stillsTotal = sse_decode_u_64(deserializer);
    var var_stillsCached = sse_decode_u_64(deserializer);
    var var_videosTotal = sse_decode_u_64(deserializer);
    var var_videosCached = sse_decode_u_64(deserializer);
    return CacheStatus(
      stillsTotal: var_stillsTotal,
      stillsCached: var_stillsCached,
      videosTotal: var_videosTotal,
      videosCached: var_videosCached,
    );
  }

  @protected
  ExportPlan sse_decode_export_plan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keeperPhotos = sse_decode_u_64(deserializer);
    var var_keeperFiles = sse_decode_u_64(deserializer);
    var var_keeperBytes = sse_decode_u_64(deserializer);
    var var_videos = sse_decode_u_64(deserializer);
    var var_videoBytes = sse_decode_u_64(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    return ExportPlan(
      keeperPhotos: var_keeperPhotos,
      keeperFiles: var_keeperFiles,
      keeperBytes: var_keeperBytes,
      videos: var_videos,
      videoBytes: var_videoBytes,
      outputPath: var_outputPath,
    );
  }

  @protected
  ExportProgress sse_decode_export_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_String(deserializer);
    var var_done = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    var var_current = sse_decode_String(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_filesCopied = sse_decode_u_64(deserializer);
    var var_filesSkipped = sse_decode_u_64(deserializer);
    var var_filesRenamed = sse_decode_u_64(deserializer);
    var var_videosCopied = sse_decode_u_64(deserializer);
    var var_videosSkipped = sse_decode_u_64(deserializer);
    var var_failures = sse_decode_list_String(deserializer);
    return ExportProgress(
      phase: var_phase,
      done: var_done,
      total: var_total,
      current: var_current,
      finished: var_finished,
      filesCopied: var_filesCopied,
      filesSkipped: var_filesSkipped,
      filesRenamed: var_filesRenamed,
      videosCopied: var_videosCopied,
      videosSkipped: var_videosSkipped,
      failures: var_failures,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IndexProgress sse_decode_index_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_String(deserializer);
    var var_done = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_photos = sse_decode_u_64(deserializer);
    var var_bursts = sse_decode_u_64(deserializer);
    var var_singles = sse_decode_u_64(deserializer);
    return IndexProgress(
      phase: var_phase,
      done: var_done,
      total: var_total,
      finished: var_finished,
      photos: var_photos,
      bursts: var_bursts,
      singles: var_singles,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BurstSummary> sse_decode_list_burst_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BurstSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_burst_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<PhotoSummary> sse_decode_list_photo_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PhotoSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_photo_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SourceInfo> sse_decode_list_source_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SourceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_source_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PhotoSummary sse_decode_photo_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_captureTimeMs = sse_decode_i_64(deserializer);
    var var_frameIndex = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_keep = sse_decode_bool(deserializer);
    var var_sharpness = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_displayPath = sse_decode_String(deserializer);
    var var_displayKind = sse_decode_String(deserializer);
    var var_thumbPath = sse_decode_opt_String(deserializer);
    var var_previewPath = sse_decode_opt_String(deserializer);
    return PhotoSummary(
      id: var_id,
      captureTimeMs: var_captureTimeMs,
      frameIndex: var_frameIndex,
      keep: var_keep,
      sharpness: var_sharpness,
      displayPath: var_displayPath,
      displayKind: var_displayKind,
      thumbPath: var_thumbPath,
      previewPath: var_previewPath,
    );
  }

  @protected
  PreprocessProgress sse_decode_preprocess_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_String(deserializer);
    var var_done = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    var var_failed = sse_decode_u_64(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_stillsProcessed = sse_decode_u_64(deserializer);
    var var_stillsSkipped = sse_decode_u_64(deserializer);
    var var_videosRendered = sse_decode_u_64(deserializer);
    var var_videosSkipped = sse_decode_u_64(deserializer);
    var var_failures = sse_decode_list_String(deserializer);
    return PreprocessProgress(
      phase: var_phase,
      done: var_done,
      total: var_total,
      failed: var_failed,
      finished: var_finished,
      stillsProcessed: var_stillsProcessed,
      stillsSkipped: var_stillsSkipped,
      videosRendered: var_videosRendered,
      videosSkipped: var_videosSkipped,
      failures: var_failures,
    );
  }

  @protected
  ProgressStats sse_decode_progress_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalBursts = sse_decode_i_64(deserializer);
    var var_decidedBursts = sse_decode_i_64(deserializer);
    var var_totalSingles = sse_decode_i_64(deserializer);
    var var_keptPhotos = sse_decode_i_64(deserializer);
    var var_keptVideos = sse_decode_i_64(deserializer);
    return ProgressStats(
      totalBursts: var_totalBursts,
      decidedBursts: var_decidedBursts,
      totalSingles: var_totalSingles,
      keptPhotos: var_keptPhotos,
      keptVideos: var_keptVideos,
    );
  }

  @protected
  SourceInfo sse_decode_source_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_rootPath = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    var var_cachePath = sse_decode_opt_String(deserializer);
    var var_lastIndexedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return SourceInfo(
      id: var_id,
      rootPath: var_rootPath,
      outputPath: var_outputPath,
      cachePath: var_cachePath,
      lastIndexedAt: var_lastIndexedAt,
    );
  }

  @protected
  SplitResult sse_decode_split_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_firstBurstId = sse_decode_i_64(deserializer);
    var var_secondBurstId = sse_decode_i_64(deserializer);
    return SplitResult(
      firstBurstId: var_firstBurstId,
      secondBurstId: var_secondBurstId,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_export_progress_Sse(
    RustStreamSink<ExportProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_index_progress_Sse(
    RustStreamSink<IndexProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_index_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_preprocess_progress_Sse(
    RustStreamSink<PreprocessProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_preprocess_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_burst_summary(BurstSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.startMs, serializer);
    sse_encode_i_64(self.endMs, serializer);
    sse_encode_i_64(self.frameCount, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fpsEstimate, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_bool(self.keepVideo, serializer);
    sse_encode_f_64(self.exportRate, serializer);
    sse_encode_i_64(self.keptCount, serializer);
    sse_encode_i_64(self.heroPhotoId, serializer);
    sse_encode_opt_String(self.heroDisplayPath, serializer);
    sse_encode_opt_String(self.heroDisplayKind, serializer);
    sse_encode_opt_String(self.heroThumbPath, serializer);
    sse_encode_opt_String(self.videoCachePath, serializer);
  }

  @protected
  void sse_encode_cache_status(CacheStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.stillsTotal, serializer);
    sse_encode_u_64(self.stillsCached, serializer);
    sse_encode_u_64(self.videosTotal, serializer);
    sse_encode_u_64(self.videosCached, serializer);
  }

  @protected
  void sse_encode_export_plan(ExportPlan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.keeperPhotos, serializer);
    sse_encode_u_64(self.keeperFiles, serializer);
    sse_encode_u_64(self.keeperBytes, serializer);
    sse_encode_u_64(self.videos, serializer);
    sse_encode_u_64(self.videoBytes, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
  }

  @protected
  void sse_encode_export_progress(
    ExportProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.phase, serializer);
    sse_encode_u_64(self.done, serializer);
    sse_encode_u_64(self.total, serializer);
    sse_encode_String(self.current, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_u_64(self.filesCopied, serializer);
    sse_encode_u_64(self.filesSkipped, serializer);
    sse_encode_u_64(self.filesRenamed, serializer);
    sse_encode_u_64(self.videosCopied, serializer);
    sse_encode_u_64(self.videosSkipped, serializer);
    sse_encode_list_String(self.failures, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_index_progress(IndexProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.phase, serializer);
    sse_encode_u_64(self.done, serializer);
    sse_encode_u_64(self.total, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_u_64(self.photos, serializer);
    sse_encode_u_64(self.bursts, serializer);
    sse_encode_u_64(self.singles, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_burst_summary(
    List<BurstSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_burst_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_photo_summary(
    List<PhotoSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_photo_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_source_info(
    List<SourceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_source_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_photo_summary(PhotoSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.captureTimeMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.frameIndex, serializer);
    sse_encode_bool(self.keep, serializer);
    sse_encode_opt_box_autoadd_f_64(self.sharpness, serializer);
    sse_encode_String(self.displayPath, serializer);
    sse_encode_String(self.displayKind, serializer);
    sse_encode_opt_String(self.thumbPath, serializer);
    sse_encode_opt_String(self.previewPath, serializer);
  }

  @protected
  void sse_encode_preprocess_progress(
    PreprocessProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.phase, serializer);
    sse_encode_u_64(self.done, serializer);
    sse_encode_u_64(self.total, serializer);
    sse_encode_u_64(self.failed, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_u_64(self.stillsProcessed, serializer);
    sse_encode_u_64(self.stillsSkipped, serializer);
    sse_encode_u_64(self.videosRendered, serializer);
    sse_encode_u_64(self.videosSkipped, serializer);
    sse_encode_list_String(self.failures, serializer);
  }

  @protected
  void sse_encode_progress_stats(ProgressStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.totalBursts, serializer);
    sse_encode_i_64(self.decidedBursts, serializer);
    sse_encode_i_64(self.totalSingles, serializer);
    sse_encode_i_64(self.keptPhotos, serializer);
    sse_encode_i_64(self.keptVideos, serializer);
  }

  @protected
  void sse_encode_source_info(SourceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.rootPath, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_opt_String(self.cachePath, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastIndexedAt, serializer);
  }

  @protected
  void sse_encode_split_result(SplitResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.firstBurstId, serializer);
    sse_encode_i_64(self.secondBurstId, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
