// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cached_path`, `to_photo_summary`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Open the library database. Call once at startup, before anything else.
Future<void> initDb({required String dbPath}) =>
    RustLib.instance.api.crateApiLibraryInitDb(dbPath: dbPath);

Future<SourceInfo> selectSource({required String rootPath}) =>
    RustLib.instance.api.crateApiLibrarySelectSource(rootPath: rootPath);

Future<List<SourceInfo>> listSources() =>
    RustLib.instance.api.crateApiLibraryListSources();

Future<void> setOutputFolder({
  required PlatformInt64 sourceId,
  required String path,
}) => RustLib.instance.api.crateApiLibrarySetOutputFolder(
  sourceId: sourceId,
  path: path,
);

Future<void> setCacheFolder({
  required PlatformInt64 sourceId,
  required String path,
}) => RustLib.instance.api.crateApiLibrarySetCacheFolder(
  sourceId: sourceId,
  path: path,
);

/// Index (or re-index) a source. Streams progress; the final event has
/// `finished = true` and the outcome counts. Runs on a dedicated thread.
Stream<IndexProgress> startIndex({required PlatformInt64 sourceId}) =>
    RustLib.instance.api.crateApiLibraryStartIndex(sourceId: sourceId);

Future<List<BurstSummary>> listBursts({
  required PlatformInt64 sourceId,
  String? statusFilter,
  required PlatformInt64 offset,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLibraryListBursts(
  sourceId: sourceId,
  statusFilter: statusFilter,
  offset: offset,
  limit: limit,
);

Future<List<PhotoSummary>> listSingles({
  required PlatformInt64 sourceId,
  required PlatformInt64 offset,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLibraryListSingles(
  sourceId: sourceId,
  offset: offset,
  limit: limit,
);

Future<List<PhotoSummary>> getBurstFrames({
  required PlatformInt64 sourceId,
  required PlatformInt64 burstId,
}) => RustLib.instance.api.crateApiLibraryGetBurstFrames(
  sourceId: sourceId,
  burstId: burstId,
);

/// Run the full upfront preprocessing pass (stills + burst videos).
/// Resumable: cached outputs are skipped, so re-running after a crash or
/// cancel picks up where it left off.
Stream<PreprocessProgress> startPreprocess({required PlatformInt64 sourceId}) =>
    RustLib.instance.api.crateApiLibraryStartPreprocess(sourceId: sourceId);

Future<void> cancelPreprocess() =>
    RustLib.instance.api.crateApiLibraryCancelPreprocess();

Future<CacheStatus> getCacheStatus({required PlatformInt64 sourceId}) =>
    RustLib.instance.api.crateApiLibraryGetCacheStatus(sourceId: sourceId);

/// Absolute paths into the preview cache for a photo, or None if missing.
Future<String?> getCachedStill({
  required PlatformInt64 sourceId,
  required PlatformInt64 photoId,
}) => RustLib.instance.api.crateApiLibraryGetCachedStill(
  sourceId: sourceId,
  photoId: photoId,
);

/// Split a burst before `at_frame_index` (frames [at..] become a new burst).
/// The affected bursts lose their cached MP4; re-run preprocessing to
/// re-render them (it skips everything else).
Future<SplitResult> splitBurst({
  required PlatformInt64 burstId,
  required PlatformInt64 atFrameIndex,
}) => RustLib.instance.api.crateApiLibrarySplitBurst(
  burstId: burstId,
  atFrameIndex: atFrameIndex,
);

/// Merge bursts into the earliest; returns the surviving burst id.
Future<PlatformInt64> mergeBursts({required Int64List burstIds}) =>
    RustLib.instance.api.crateApiLibraryMergeBursts(burstIds: burstIds);

/// Re-run automatic grouping with a new gap. Manually split/merged bursts
/// are locked and untouched. Returns the number of new bursts formed.
Future<BigInt> regroup({
  required PlatformInt64 sourceId,
  required PlatformInt64 gapMs,
  required PlatformInt64 minBurstLen,
}) => RustLib.instance.api.crateApiLibraryRegroup(
  sourceId: sourceId,
  gapMs: gapMs,
  minBurstLen: minBurstLen,
);

Future<String?> getAppSetting({required String key}) =>
    RustLib.instance.api.crateApiLibraryGetAppSetting(key: key);

Future<void> setAppSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiLibrarySetAppSetting(key: key, value: value);

Future<void> setFrameKeep({required Int64List photoIds, required bool keep}) =>
    RustLib.instance.api.crateApiLibrarySetFrameKeep(
      photoIds: photoIds,
      keep: keep,
    );

/// status: "undecided" | "done" | "rejected"
Future<void> setBurstStatus({
  required PlatformInt64 burstId,
  required String status,
}) => RustLib.instance.api.crateApiLibrarySetBurstStatus(
  burstId: burstId,
  status: status,
);

Future<void> setKeepVideo({
  required PlatformInt64 burstId,
  required bool keep,
}) => RustLib.instance.api.crateApiLibrarySetKeepVideo(
  burstId: burstId,
  keep: keep,
);

Future<ProgressStats> getProgressStats({required PlatformInt64 sourceId}) =>
    RustLib.instance.api.crateApiLibraryGetProgressStats(sourceId: sourceId);

Future<ExportPlan> planExport({required PlatformInt64 sourceId}) =>
    RustLib.instance.api.crateApiLibraryPlanExport(sourceId: sourceId);

Stream<ExportProgress> startExport({required PlatformInt64 sourceId}) =>
    RustLib.instance.api.crateApiLibraryStartExport(sourceId: sourceId);

Future<void> cancelExport() =>
    RustLib.instance.api.crateApiLibraryCancelExport();

class BurstSummary {
  final PlatformInt64 id;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final PlatformInt64 frameCount;
  final double? fpsEstimate;

  /// "undecided" | "done" | "rejected"
  final String status;
  final bool keepVideo;
  final PlatformInt64 keptCount;
  final PlatformInt64 heroPhotoId;

  /// Absolute path of a representative frame's display file, if usable.
  final String? heroDisplayPath;
  final String? heroDisplayKind;

  /// Cached 320px thumb of the hero frame (preferred for display).
  final String? heroThumbPath;
  final String? videoCachePath;

  const BurstSummary({
    required this.id,
    required this.startMs,
    required this.endMs,
    required this.frameCount,
    this.fpsEstimate,
    required this.status,
    required this.keepVideo,
    required this.keptCount,
    required this.heroPhotoId,
    this.heroDisplayPath,
    this.heroDisplayKind,
    this.heroThumbPath,
    this.videoCachePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      frameCount.hashCode ^
      fpsEstimate.hashCode ^
      status.hashCode ^
      keepVideo.hashCode ^
      keptCount.hashCode ^
      heroPhotoId.hashCode ^
      heroDisplayPath.hashCode ^
      heroDisplayKind.hashCode ^
      heroThumbPath.hashCode ^
      videoCachePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BurstSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          frameCount == other.frameCount &&
          fpsEstimate == other.fpsEstimate &&
          status == other.status &&
          keepVideo == other.keepVideo &&
          keptCount == other.keptCount &&
          heroPhotoId == other.heroPhotoId &&
          heroDisplayPath == other.heroDisplayPath &&
          heroDisplayKind == other.heroDisplayKind &&
          heroThumbPath == other.heroThumbPath &&
          videoCachePath == other.videoCachePath;
}

class CacheStatus {
  final BigInt stillsTotal;
  final BigInt stillsCached;
  final BigInt videosTotal;
  final BigInt videosCached;

  const CacheStatus({
    required this.stillsTotal,
    required this.stillsCached,
    required this.videosTotal,
    required this.videosCached,
  });

  @override
  int get hashCode =>
      stillsTotal.hashCode ^
      stillsCached.hashCode ^
      videosTotal.hashCode ^
      videosCached.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheStatus &&
          runtimeType == other.runtimeType &&
          stillsTotal == other.stillsTotal &&
          stillsCached == other.stillsCached &&
          videosTotal == other.videosTotal &&
          videosCached == other.videosCached;
}

class ExportPlan {
  final BigInt keeperPhotos;
  final BigInt keeperFiles;
  final BigInt keeperBytes;
  final BigInt videos;
  final BigInt videoBytes;
  final String? outputPath;

  const ExportPlan({
    required this.keeperPhotos,
    required this.keeperFiles,
    required this.keeperBytes,
    required this.videos,
    required this.videoBytes,
    this.outputPath,
  });

  @override
  int get hashCode =>
      keeperPhotos.hashCode ^
      keeperFiles.hashCode ^
      keeperBytes.hashCode ^
      videos.hashCode ^
      videoBytes.hashCode ^
      outputPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportPlan &&
          runtimeType == other.runtimeType &&
          keeperPhotos == other.keeperPhotos &&
          keeperFiles == other.keeperFiles &&
          keeperBytes == other.keeperBytes &&
          videos == other.videos &&
          videoBytes == other.videoBytes &&
          outputPath == other.outputPath;
}

class ExportProgress {
  /// "keepers" | "videos" | "done"
  final String phase;
  final BigInt done;
  final BigInt total;
  final String current;
  final bool finished;
  final BigInt filesCopied;
  final BigInt filesSkipped;
  final BigInt filesRenamed;
  final BigInt videosCopied;
  final BigInt videosSkipped;
  final List<String> failures;

  const ExportProgress({
    required this.phase,
    required this.done,
    required this.total,
    required this.current,
    required this.finished,
    required this.filesCopied,
    required this.filesSkipped,
    required this.filesRenamed,
    required this.videosCopied,
    required this.videosSkipped,
    required this.failures,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      done.hashCode ^
      total.hashCode ^
      current.hashCode ^
      finished.hashCode ^
      filesCopied.hashCode ^
      filesSkipped.hashCode ^
      filesRenamed.hashCode ^
      videosCopied.hashCode ^
      videosSkipped.hashCode ^
      failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          done == other.done &&
          total == other.total &&
          current == other.current &&
          finished == other.finished &&
          filesCopied == other.filesCopied &&
          filesSkipped == other.filesSkipped &&
          filesRenamed == other.filesRenamed &&
          videosCopied == other.videosCopied &&
          videosSkipped == other.videosSkipped &&
          failures == other.failures;
}

class IndexProgress {
  final String phase;
  final BigInt done;
  final BigInt total;
  final bool finished;

  /// Set on the final event.
  final BigInt photos;
  final BigInt bursts;
  final BigInt singles;

  const IndexProgress({
    required this.phase,
    required this.done,
    required this.total,
    required this.finished,
    required this.photos,
    required this.bursts,
    required this.singles,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      done.hashCode ^
      total.hashCode ^
      finished.hashCode ^
      photos.hashCode ^
      bursts.hashCode ^
      singles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          done == other.done &&
          total == other.total &&
          finished == other.finished &&
          photos == other.photos &&
          bursts == other.bursts &&
          singles == other.singles;
}

class PhotoSummary {
  final PlatformInt64 id;
  final PlatformInt64 captureTimeMs;
  final PlatformInt64? frameIndex;
  final bool keep;
  final double? sharpness;

  /// Absolute path of the best original file for direct display
  /// (JPEG > HEIF > RAW). Fallback when the cache is incomplete.
  final String displayPath;

  /// "raw" | "jpeg" | "heif" — raw means Flutter can't Image.file it.
  final String displayKind;

  /// Cached 320px thumb (preferred for grids/filmstrips).
  final String? thumbPath;

  /// Cached 2048px preview (paused-frame overlay, zoom).
  final String? previewPath;

  const PhotoSummary({
    required this.id,
    required this.captureTimeMs,
    this.frameIndex,
    required this.keep,
    this.sharpness,
    required this.displayPath,
    required this.displayKind,
    this.thumbPath,
    this.previewPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      captureTimeMs.hashCode ^
      frameIndex.hashCode ^
      keep.hashCode ^
      sharpness.hashCode ^
      displayPath.hashCode ^
      displayKind.hashCode ^
      thumbPath.hashCode ^
      previewPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhotoSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          captureTimeMs == other.captureTimeMs &&
          frameIndex == other.frameIndex &&
          keep == other.keep &&
          sharpness == other.sharpness &&
          displayPath == other.displayPath &&
          displayKind == other.displayKind &&
          thumbPath == other.thumbPath &&
          previewPath == other.previewPath;
}

class PreprocessProgress {
  /// "stills" | "videos" | "done"
  final String phase;
  final BigInt done;
  final BigInt total;
  final BigInt failed;
  final bool finished;

  /// Populated on the final event.
  final BigInt stillsProcessed;
  final BigInt stillsSkipped;
  final BigInt videosRendered;
  final BigInt videosSkipped;
  final List<String> failures;

  const PreprocessProgress({
    required this.phase,
    required this.done,
    required this.total,
    required this.failed,
    required this.finished,
    required this.stillsProcessed,
    required this.stillsSkipped,
    required this.videosRendered,
    required this.videosSkipped,
    required this.failures,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      done.hashCode ^
      total.hashCode ^
      failed.hashCode ^
      finished.hashCode ^
      stillsProcessed.hashCode ^
      stillsSkipped.hashCode ^
      videosRendered.hashCode ^
      videosSkipped.hashCode ^
      failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreprocessProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          done == other.done &&
          total == other.total &&
          failed == other.failed &&
          finished == other.finished &&
          stillsProcessed == other.stillsProcessed &&
          stillsSkipped == other.stillsSkipped &&
          videosRendered == other.videosRendered &&
          videosSkipped == other.videosSkipped &&
          failures == other.failures;
}

class ProgressStats {
  final PlatformInt64 totalBursts;
  final PlatformInt64 decidedBursts;
  final PlatformInt64 totalSingles;
  final PlatformInt64 keptPhotos;
  final PlatformInt64 keptVideos;

  const ProgressStats({
    required this.totalBursts,
    required this.decidedBursts,
    required this.totalSingles,
    required this.keptPhotos,
    required this.keptVideos,
  });

  @override
  int get hashCode =>
      totalBursts.hashCode ^
      decidedBursts.hashCode ^
      totalSingles.hashCode ^
      keptPhotos.hashCode ^
      keptVideos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressStats &&
          runtimeType == other.runtimeType &&
          totalBursts == other.totalBursts &&
          decidedBursts == other.decidedBursts &&
          totalSingles == other.totalSingles &&
          keptPhotos == other.keptPhotos &&
          keptVideos == other.keptVideos;
}

class SourceInfo {
  final PlatformInt64 id;
  final String rootPath;
  final String? outputPath;
  final String? cachePath;
  final PlatformInt64? lastIndexedAt;

  const SourceInfo({
    required this.id,
    required this.rootPath,
    this.outputPath,
    this.cachePath,
    this.lastIndexedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rootPath.hashCode ^
      outputPath.hashCode ^
      cachePath.hashCode ^
      lastIndexedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rootPath == other.rootPath &&
          outputPath == other.outputPath &&
          cachePath == other.cachePath &&
          lastIndexedAt == other.lastIndexedAt;
}

class SplitResult {
  final PlatformInt64 firstBurstId;
  final PlatformInt64 secondBurstId;

  const SplitResult({required this.firstBurstId, required this.secondBurstId});

  @override
  int get hashCode => firstBurstId.hashCode ^ secondBurstId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SplitResult &&
          runtimeType == other.runtimeType &&
          firstBurstId == other.firstBurstId &&
          secondBurstId == other.secondBurstId;
}
